language: node_js
node_js:
- iojs-v2.5.0
branches:
  only:
  - master
install:
  - npm install
script:
  - webpack
after_success:
  - cd dist
  -
  - git init
  - git config user.name "$GH_USER"
  - git config user.email "$GH_EMAIL"
  -
  - git checkout --orphan gh-pages
  -
  - git add .
  - git commit -m "new build"
  - git push --force --quiet "https://$GH_TOKEN@$GH_REF" gh-pages > /dev/null 2>&1
notifications:
  email:
  - fredrik.orback@find-out.se